// Register all controllers
// Stimulus application is already started in application.js

// Register controllers dynamically
Promise.all([
  import("controllers/checkbox_group_controller"),
  import("controllers/clip_escape_controller"),
  import("controllers/clip_rate_controller"),
  import("controllers/clipboard_controller"),
  import("controllers/discover_item_controller"),
  import("controllers/element_hide_controller"),
  import("controllers/feed_item_controller"),
  import("controllers/feed_nav_controller"),
  import("controllers/feed_rate_controller"),
  import("controllers/flash_controller"),
  import("controllers/folder_toggle_controller"),
  import("controllers/folder_toggle_template_controller"),
  import("controllers/form_validation_controller"),
  import("controllers/hotkey_controller"),
  import("controllers/item_close_controller"),
  import("controllers/item_close_next_controller"),
  import("controllers/item_pin_toggle_controller"),
  import("controllers/keyboard_nav_controller"),
  import("controllers/keyhelp_controller"),
  import("controllers/manage_controller"),
  import("controllers/mark_read_controller"),
  import("controllers/menu_item_controller"),
  import("controllers/menu_toggle_controller"),
  import("controllers/password_match_controller"),
  import("controllers/pin_button_controller"),
  import("controllers/pin_controller"),
  import("controllers/pin_item_controller"),
  import("controllers/pin_remove_controller"),
  import("controllers/prevent_submit_controller"),
  import("controllers/rate_pad_controller"),
  import("controllers/reader_controller"),
  import("controllers/reader_pin_controller"),
  import("controllers/share_controller"),
  import("controllers/show_all_controller"),
  import("controllers/sortmode_toggle_controller"),
  import("controllers/subs_item_controller"),
  import("controllers/subs_reload_controller"),
  import("controllers/subscribe_form_controller"),
  import("controllers/subscription_controller"),
  import("controllers/subscription_item_controller"),
  import("controllers/subscription_list_controller"),
  import("controllers/tab_controller"),
  import("controllers/tips_controller"),
  import("controllers/viewmode_toggle_controller"),
]).then(modules => {
  const application = window.Stimulus
  if (!application) {
    console.error("Stimulus application not found on window.Stimulus")
    return
  }
  const names = [
    "checkbox-group",
    "clip-escape",
    "clip-rate",
    "clipboard",
    "discover-item",
    "element-hide",
    "feed-item",
    "feed-nav",
    "feed-rate",
    "flash",
    "folder-toggle",
    "folder-toggle-template",
    "form-validation",
    "hotkey",
    "item-close",
    "item-close-next",
    "item-pin-toggle",
    "keyboard-nav",
    "keyhelp",
    "manage",
    "mark-read",
    "menu-item",
    "menu-toggle",
    "password-match",
    "pin-button",
    "pin",
    "pin-item",
    "pin-remove",
    "prevent-submit",
    "rate-pad",
    "reader",
    "reader-pin",
    "share",
    "show-all",
    "sortmode-toggle",
    "subs-item",
    "subs-reload",
    "subscribe-form",
    "subscription",
    "subscription-item",
    "subscription-list",
    "tab",
    "tips",
    "viewmode-toggle",
  ]
  modules.forEach((module, index) => {
    application.register(names[index], module.default)
  })
  console.log("Stimulus controllers registered:", names.length)
}).catch(error => {
  console.error("Failed to load Stimulus controllers:", error)
})
